<?php
/**
 * Created by PhpStorm.
 * User: ivan
 * Date: 10.04.18
 * Time: 5:12 PM
 */

namespace app\components\widgets;


use app\modules\content\models\Content;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;

class BreadcumsWidget extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        if (\Yii::$app->controller->module->id === 'basepage') {
            return false;
        }

        $result = [];

        switch (\Yii::$app->controller->module->id) {
            case 'content' :

                $contentId = \Yii::$app->request->get('id');

                if ($contentId) {
                    $model = Content::findOne($contentId);

                    if ($model !== null) {
                        $result[] = $model->title;
                    }

                }

            break;
        }

        if (empty($result)) {
            return false;
        }

        return $this->render('breadCumsWidget', ['result' => $result]);
    }
}