<?php
/**
 * Created by PhpStorm.
 * User: ivan
 * Date: 10.04.18
 * Time: 5:12 PM
 */

namespace app\components\widgets;


use app\modules\content\models\Content;
use app\modules\histories\models\Histories;
use app\modules\pages\models\Pages;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;

class BreadcumsWidget extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        if (\Yii::$app->controller->module->id === 'basepage') {
            return false;
        }

        $result = [];

        switch (\Yii::$app->controller->module->id) {
            case 'content' :
                switch (\Yii::$app->controller->action->id) {
                    case 'view':
                        $contentId = \Yii::$app->request->get('id');

                        if ($contentId) {
                            $model = Content::findOne($contentId);

                            if ($model !== null) {
                                $result[] = $model->title;
                            }
                        }
                        break;
                    case 'contact':
                        $result[] = 'Контакты';
                    break;
                }

            break;
            case 'pages':
                switch (\Yii::$app->controller->action->id) {
                    case 'news':
                        $result[] = 'Новости';
                        break;
                    case 'news-view':
                        $result[] = '<a href="/news/">Новости</a>';

                        $newsId = \Yii::$app->request->get('id');
                        $model = Pages::findOne($newsId);

                        if ($model !== null) {
                            $result[] = $model->title;
                        }
                        break;
                    case 'info-view':
                        $result[] = '<a href="/info/">Полезная информация</a>';

                        $newsId = \Yii::$app->request->get('id');
                        $model = Pages::findOne($newsId);

                        if ($model !== null) {
                            $result[] = $model->title;
                        }
                        break;
                    case 'info':
                        $result[] = 'Полезная информация';
                        break;
                    case 'programms':
                        $result[] = 'Программы фонда';
                        break;
                }
            break;
            case 'histories':
                switch(\Yii::$app->controller->action->id) {
                    case 'index':
                        $result[] = 'Живые истории';
                        break;
                    case 'view':
                        $result[] = '<a href="/histories/">Живые истории</a>';

                        $newsId = \Yii::$app->request->get('id');
                        $model = Histories::findOne($newsId);

                        if ($model !== null) {
                            $result[] = $model->title;
                        }
                        break;
                }
            break;
        }

        if (empty($result)) {
            return false;
        }

        return $this->render('breadCumsWidget', ['result' => $result]);
    }
}