<?php
/**
 * Created by PhpStorm.
 * User: MOZART
 * Date: 09.04.2018
 * Time: 21:18
 */

namespace app\components\widgets;

use app\modules\galleries\models\Galleries;
use yii\base\Widget;

class SliderWidget extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        if (\Yii::$app->controller->module->id !== 'basepage') {
            return false;
        }

        $slider = Galleries::find()->where(['is_active' => 1, 'sefname' => 'slider'])->one();

        if (!$slider) {
            return false;
        }

        if (!$slider->images) {
            return false;
        }

        return $this->render('sliderWidget', ['slider' => $slider]);
    }
}