<?php
/**
 * Created by PhpStorm.
 * User: ivan
 * Date: 10.04.18
 * Time: 3:16 PM
 */

namespace app\modules\galleries\front\components\widgets;


use app\modules\galleries\models\Galleries;
use yii\base\Widget;

class BasepageGalleryWidget extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $gallery = Galleries::find()->where(['is_active' => 1, 'sefname' => 'basepage_photo'])->one();
        $videoGallery = Galleries::find()->where(['is_active' => 1, 'sefname' => 'basepage_video'])->one();

        if ($gallery === null || $videoGallery === null) {
            return false;
        }

        return $this->render('basepageGalleryWidget', ['gallery' => $gallery, 'videoGallery' => $videoGallery]);
    }
}