<?php
/**
 * Created by PhpStorm.
 * User: ivan
 * Date: 27.04.18
 * Time: 11:38 AM
 */

namespace app\modules\poll;


use mtemplate\mclasses\MBTModule;

class Module extends MBTModule
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}